server:
  port: 8081

spring:
  application:
    name: national-health-registry-service
  datasource:
    # Looks for Docker env variable first; falls back to localhost if run inside IDE
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/registry_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect